name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

permissions:
  # required in case of tags to update releases
  contents: write

jobs:
  # see https://github.com/esphome/esphome-project-template/tree/main/.github/workflows
  build:
    name: Build ESPHome project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: ESPHome
        uses: esphome/build-action@v7
        with:
          yaml-file: example-instance.yaml
          version: stable
      - name: Upload files to release
        uses: softprops/action-gh-release@v3.0.3
        if: github.ref_type == 'tag'
        with:
          files: |
            */*.ota.bin
            */*.factory.bin
